### ISSUE TITLE
Tuning completed early

### ISSUE THREAD

**Issue by markusruhsam** [stevemussmann/BA3-SNPS-autotune#1]
Hello,

I ran autotune with `./BA3-SNPS-autotune.py -i myfilename.str.immanc -l 2271 -b 10000 -g 100000` and although there should have been 15 rounds the program  finished without an error early after 4. Just was wondering whether this can happen/is normal?

> ##Tuning completed early after 4 rounds.
##M	A	F
0.2125	0.7750	0.0625

Thanks

Markus

**Comment by stevemussmann** [comment]
Hi Markus,

This sounds like expected behavior. The number of rounds that is specified
is a maximum number to prevent the program from running forever if it
encounters a dataset that cannot be optimized (which happens rarely). Once
it encounters  optimal parameters the program will stop running and report
them. In my publication for the program I have a bar plot that shows 3-4
rounds of optimization is normal for most datasets.

-Steve

**Comment by markusruhsam** [comment]
Excellent – thanks very much for the quick reply!

Markus
