### ISSUE TITLE
-m/-a/-f arguments for autotune

### ISSUE THREAD

**Issue by ericopolo** [stevemussmann/BA3-SNPS-autotune#3]
Dear Dr. Mussmann,

I've been using BA3-SNPS-autotune for a while now, and it's being very useful, thanks! But most of the times I have no idea about how long the chain should be to get close to convergence, so I have to repeat the analysis with longer lengths. An inconvenience I face when I do that is that the mixing parameters are back to default values (0.1), and they must repeat all their way back to the best values found so far before they get a chance to be updated again. The solution I found was extremely simple and it's saving me a lot of time, so I thought it would be a good idea to suggest it as an official update. I simply edited your scripts (BA3-SNPS-autotune.py, bayesass.py and comline.py) to allow different starting points for the mixing parameters (m, a and f), so I pass them to autotune with the values I found on the last "run", the same way I would do with bayesass. What do you think?

Cheers,

Érico.

**Comment by stevemussmann** [comment]
Hi Érico,

Thank you for looking for ways to make improvements - I'm potentially interested in merging your changes but have a few questions.

My experience has been that running long chain lengths in BA3-SNPS-autotune haven't been necessary - I usually run at the defaults (which are set at 10k generations) and through the hundreds of files I have run up to this point I haven't had issues with the mixing parameters determined by these short runs to fall outside of the values recommended in the BA3 manual. This is because the autotune algorithm is designed to favor acceptance rates in the center of the range suggested in that manual, so there is some room for change if the acceptance rates stray post-convergence from the values observed during the autotune program. So far, I have based my mixing parameter choices on these short runs and have checked after completing long runs (40 million+ generations), and the acceptance values have always stayed within those suggested by the original BA3 manual. 

Also, the autotune algorithm is essentially a binary search, so it quickly eliminates suboptimal mixing parameters. In my experience, most data files that require more than ~5 rounds of optimization are files for which optimal mixing parameters will never be found. That is because the algorithm makes large jumps in the first 2-3 rounds of optimization, then makes increasingly fine adjustments thereafter. 

If you have some data showing that longer runs or different starting mixing parameters help, I am open to incorporating these changes. However, two of the biggest misconceptions I've had to fight regarding this program are that 1) in my experience, long chain lengths aren't necessary for determining the mixing parameters, and 2) >5 rounds of optimization is not necessarily improving mixing parameter estimates. I've had people contact me before indicating that the autotune program was taking a long time to run, and after asking some questions I usually find the problem relates to at least one of these two issues (because people often think more = better). I always feel bad when this happens, because the intent of the program is to be a time saver. As a result, I've worked to update the documentation to indicate that long runs / many rounds of optimization are not necessary, so my motivation is that I do not want to provide mixed messages that will conflict with those principles.
