### ISSUE TITLE
Unexpected Error with 1st Usage

### ISSUE THREAD

**Issue by mitmcglaughlin** [stevemussmann/BA3-SNPS-autotune#5]
Hi Steve,

Thank you for developing this program. I am trying to get Auotune working. I can already run BA3-SNP, but would like to use autotune for mixing parameters. I am trying to run your example file and I get the following:

(base) mcglaughlinlab@nhs21-2228 BayesAss3-SNPs-1.1 % ./BA3-SNPS-autotune.py -i spd_ARU+182+BOU.str.immanc -l 4819 -r 5
Running repetition 1 of 5
BA3-SNPS -F spd_ARU+182+BOU.str.immanc -l 4819 -i 10000 -s 10 -b 1000 -m 0.1000000000000000055511151231257827021181583404541015625 -a 0.1000000000000000055511151231257827021181583404541015625 -f 0.1000000000000000055511151231257827021181583404541015625 -o output.txt -t -v -g -u
Non-zero exit status:
-6
Unexpected error:
(<class 'SystemExit'>, SystemExit(), <traceback object at 0x7fa219547c40>)

I did have to update the Path to python3 in the .py file with my path being:
/Users/mcglaughlinlab/opt/miniconda3/bin/python3

I am not sure if it is Miniconda issue or something else. Also if of interest I am running via MacOSX terminal.

Thanks!  Mit

**Comment by stevemussmann** [comment]
Hi Mit,

I'm not sure what is causing this problem. It appears to be happening when BA3-SNPs is called from inside the autotune program. The "Non-zero exit status" message indicates that the error came from BA3-SNPs. Since you said you were able to run BA3-SNPs just fine on its own, I guess I would suggest checking that 1) The executable for BA3-SNPs is installed with the exact case used here in the system call (i.e., BA3-SNPS) and make sure the file you are trying to analyze (in this case, spd_ARU+182+BOU.str.immanc) is properly named and present in the directory from where you are trying to call the program. Again, nothing is jumping out at me as an obvious problem, so my best guess is that something either 1) isn't being found by BA3-SNPs-autotune or 2) something was entered erroneously as input to BA3-SNPs-autotune (e.g., a file path), and that error is being passed through to the BA3-SNPs program. 

-Steve
