### ISSUE TITLE
Bad trace file and final results?

### ISSUE THREAD

**Issue by jbernst** [stevemussmann/BA3-SNPS-autotune#7]
Hello! 

I have more of a general question on running BA3-SNPS-autotune. I currently of a pretty large dataset (I know it is better to work with smaller ones, but I still need to figure out how to parse it down, though I am working with computers with very large storage and RAM): 276 individuals, 17 populations, 27281 loci, 0 missing genotypes. 

I was first running BA3-SNPs and changing parameters but then realized there was the autotune you had created. I ran it on my datafile and it ran within 2 hours. 

My question is that when I run BA3-SNPS-autotune, does it just give you the parameters to use for an actual BA3-SNPS run, or does the autotune version run the final version as well (to my understanding this is what it does, but perhaps I am mistaken)?

I ran it as just `./BA3-SNPS-autotune.py --file infile.inp --loci 27281` and it ran to completion within 3 runs of autotune. It suggested the following:
```
##Tuning completed early after 3 rounds.
##M     A       F
0.1000  0.3250  0.0250
```
The odd thing is that the trace file I got only shows one single line for the entire trace. I have attached the trace file, and also am attaching my immanc file (the `infile.inp.txt`, which in mycomputer is infile.inp but I had to change the extension to attach it here). I only am showing the first 1000 lines of the `infile.inp` due to its size. Is this because I didn't set particular parameters? Was I supposed to or is the way I ran the analysis a good 'final' way to get the results I need? If any other files are needed, please let me know.

[infile.trace.txt](https://github.com/stevemussmann/BA3-SNPS-autotune/files/13384709/infile.trace.txt)
[infile.inp.txt](https://github.com/stevemussmann/BA3-SNPS-autotune/files/13384681/infile.inp.txt)

Thank you!

Justin

**Comment by stevemussmann** [comment]
Hi Justin,

The autotune program will only give you the parameters for your run. It does not conduct the final run for you. The reason for this is because the mixing parameters seem to be more tied to the properties of your input file rather than the the number of MCMC iterations, so you can [usually] get away with doing very short runs to tune the mixing parameters. It's exceedingly rare (in my experience) that you need to do longer runs for tuning mixing values. Anyways, this means that you will have to do a longer run to get your 'final' results.

The trace file output from the autotune runs might just appear as a single line because those runs are typically pretty short (a few thousand MCMC iterations). That likely wasn't enough for the MCMC to go through burn-in yet, and with 17 populations the MCMC might run into some problems sampling parameter space. So, in other words, the result you got seems normal enough to me, given that it came from a very short run of the program.

**Comment by jbernst** [comment]
Hi Steve,

Thanks so much for replying so quickly! I am excited to run my analysis. One more question (for now, but hopefully this is it): I am running the analysis with the recommended parameters I obtained from autotune. I also am having it run for 10 million generations. It is currently halfway done with the analysis and I see that my output on the terminal is:

`logP(M): -834.05 logL(G): -1954608.25 logL: -1955442.30 % done: (0.50) % accepted: (0.53, 0.00, 0.55, 0.54, 0.00)`

I presume that these values greater than zero will exceed 0.60 by tomorrow. Should I changed my parameters to reduce this, so as to stay within the recommended 20% to 60% acceptance values? Or should I keep this as a final result for my research since these were obtained from autotune? (PS - I noticed that in the BA3-SNPs documentation is states inbreeding coefficients are still too high at 45%; why is this given that it is between 20% and 60%?)

Thanks again!

**Comment by stevemussmann** [comment]
You have no control over those parameters that are reading as 0.00 because they are discrete parameters. They may never get within 'optimal' values and the only real solution in that case is running the MCMC longer. The original BayesAss manual provides an explanation (https://github.com/brannala/BA3/wiki#52-adjustment-of-mixing-parameters).

I think in the original documentation they were trying to keep the acceptance at or under 40%. If you're in the recommended range (20% to 60%) then I wouldn't worry too much. There are some datasets that never reach optimal acceptance values.

**Comment by jbernst** [comment]
Hi Steve,

Great! The analysis just finished and the parameter acceptance rates are `(0.58, 0.00, 0.61, 0.60, and 0.00)`. Given these being just at the upper threshold of the acceptance rates we wants, should I take the autotune suggested flags and just increase the values?

Autotune suggested the following:
```
##Tuning completed early after 3 rounds.
##M     A       F
0.1000  0.3250  0.0250
```

So I am thinking of changing the acceptance rates to, say, 0.15, 0.35, and 0.05. And then, if I get my acceptance rates between 20% and 60%, use that run as my final results. Does that sound like a reasonable plan? The code below is what I plan to run:
`./BA3-SNPS -m0.1500 -a0.3500 -f0.0500 --file Ingroup_Full.inp --loci 27281 -s100 -i10000000 -b1000000 -n100 -o Ingroup_Full_outfile -t -v -u`

**Comment by stevemussmann** [comment]
You might try re-running with those parameters, although if you look at the traces in Tracer and have reasonable ESS values then there's probably not a huge need to rerun.

**Comment by jbernst** [comment]
I just checked the trace file and there is something that isn't right. I ran the last analysis as `./BA3-SNPS -a0.3250 -f0.0250 --file Ingroup_Full.inp --loci 27281 -s100 -i10000000 -b1000000 -n100 -o Ingroup_Full_outfile -t -v -u` and yet this is what my trace file looks like (attached0. Why does the trace look like this rather than the typical trace file 'caterpillar' we expect' (assuming convergence). And for ESS values, are we viewing 200+ as good ESS similar to other Bayesian analyses?

I appreciate your help on this. If there is other information that would be helpful, let me know and I am happy to provide it!

<img width="1186" alt="Screenshot 2023-11-20 at 5 40 25 PM" src="https://github.com/stevemussmann/BA3-SNPS-autotune/assets/16763636/0a8b42c8-b6bf-4cd9-a694-c8485fabe9a9">

**Comment by stevemussmann** [comment]
My best guess is that it's having trouble with trying to run 17(?) populations through the program, so it's not reaching convergence. See Meirmans 2014 (https://onlinelibrary.wiley.com/doi/10.1111/1755-0998.12216). If there's a way to partition your dataset to run subsets of populations through it, such as if you can definitively say that certain groups of populations will never contact one another due to impenetrable barriers, then you might be able to divide your populations along those lines. 

As far as ESS - yes, if you are getting at least 200 that should be sufficient.

**Comment by jbernst** [comment]
Thank you for adding the Meirmans 2014 link in here. I will give this a read! I just checked the newest run using:
`./BA3-SNPS -m0.1500 -a0.3500 -f0.0500 --file Ingroup_Full.inp --loci 27281 -s100 -i10000000 -b1000000 -n100 -o Ingroup_Full_outfile -t -v -u` and the resulting acceptance rates look good:
```
logP(M): -824.16 logL(G): -1832304.38 logL: -1833128.54 % done: (0.10) % accepted: (0.34, 0.00, 0.41, 0.25, 0.00)
logP(M): -807.29 logL(G): -1893616.76 logL: -1894424.05 % done: (0.20) % accepted: (0.38, 0.00, 0.44, 0.32, 0.00)
logP(M): -810.77 logL(G): -1922281.66 logL: -1923092.43 % done: (0.30) % accepted: (0.41, 0.00, 0.48, 0.36, 0.00)
logP(M): -810.52 logL(G): -1939708.82 logL: -1940519.35 % done: (0.40) % accepted: (0.44, 0.00, 0.51, 0.39, 0.00)
logP(M): -839.93 logL(G): -1950635.62 logL: -1951475.55 % done: (0.50) % accepted: (0.46, 0.00, 0.53, 0.41, 0.00)
logP(M): -854.05 logL(G): -1960008.61 logL: -1960862.67 % done: (0.60) % accepted: (0.47, 0.00, 0.54, 0.43, 0.00)
logP(M): -849.77 logL(G): -1965862.58 logL: -1966712.35 % done: (0.70) % accepted: (0.48, 0.00, 0.56, 0.45, 0.00)
logP(M): -874.32 logL(G): -1969648.83 logL: -1970523.15 % done: (0.80) % accepted: (0.50, 0.00, 0.57, 0.46, 0.00)
logP(M): -878.77 logL(G): -1971262.73 logL: -1972141.49 % done: (0.90) % accepted: (0.51, 0.00, 0.58, 0.48, 0.00)
logP(M): -870.05 logL(G): -1973993.55 logL: -1974863.60 % done: (1.00) % accepted: (0.52, 0.00, 0.60, 0.49, 0.00)
```
I would like to check with you if my results are anything I can improve or if I can trust these. Below are three screenshots from Tracer. Most traces have ESS values that have drastically improved, but some models for migration stats are below 100 or 200. I notice the trace jumps in those, but for the ESS values >200 for other migration stats, they seem to be okay (can you let me know if you agree with this and that I am interpreting this correctly?). Also, the LogProb is a very low ESS...does this negate any of the other ESS >200? How can I improve on this? Out of 256 combinations for comparing populations, only 14 had ESS <100 and an additional 3 had ESS <200.

Photo 1: LogProb Trace
<img width="1180" alt="Screenshot 2023-11-30 at 10 32 38 AM" src="https://github.com/stevemussmann/BA3-SNPS-autotune/assets/16763636/56e21bec-7b5b-4c5e-9922-882528c94442">

Photo 2: Example of ESS >200 
<img width="1182" alt="Screenshot 2023-11-30 at 10 32 54 AM" src="https://github.com/stevemussmann/BA3-SNPS-autotune/assets/16763636/f69733cc-1cb8-4409-b9b3-83ef14a24123">

Photo 3: Example of ESS <100
<img width="1185" alt="Screenshot 2023-11-30 at 10 33 01 AM" src="https://github.com/stevemussmann/BA3-SNPS-autotune/assets/16763636/564f0c82-cfb0-4c17-b477-0ccca898d725">

**Comment by stevemussmann** [comment]
I would interpret that as still not reaching convergence, and probably wouldn't trust the results. With having so many populations in your analysis it might take a very long time to reach convergence (possibly 10s of millions of generations) - if ever - given the results you have seen so far and the number of parameters that are being estimated simultaneously.

**Comment by jbernst** [comment]
Okay, I will rerun this and will work on seeing how we can cut populations from our input file to reduce the number of comparisons it needs to make. Thank you! I will leave this open for now and repost in here once I get to this (unless you rather it be closed, then that is fine too).

**Comment by stevemussmann** [comment]
I'm closing this issue since it seems to no longer be active. Feel free to re-open, or open a new issue if you experience problems.

-Steve
